nelmio_api_doc:
    documentation:
        info:
            title: API Documentation
            description: Basic API
            version: 1.0.0
    areas: # to filter documented areas
        default:
          path_patterns: [ ^/orders ]
